// <auto-generated />
namespace ITI.WhatsLearn.Reposatories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tes));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271357226_tes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
